### ISSUE TITLE
Wiring ground and power?

### ISSUE THREAD

**Issue by DapperFactory** [alexhagiopol/public#1]
Hey Alex great job. I had started my own project using a joystick a few months ago when I was using a hk flight board. Recently I bought the naza and found your site!

How are you wiring the naza to the mega in regards to the ground and +5 for the flight control inputs (throat, rudder, ..etc)?
Are you running power +5 to the naza flight control inputs  from the mega? Or just sending the signal?

**Comment by alexhagiopol** [comment]
Take a look at this page on my website and scroll down until you see the circuit diagram: http://alexhagiopol.com/portfolio/arduino-quadcopter-2-0-gps-live-demo/

I use the DJI Naza to provide power to the Mega through the Mega's +5V pin.
